/**
 * Global brand themes defining the 6 core color palettes.
 * Used across features to maintain the "Construcción Identitaria" visual language.
 */
export const BRAND_THEMES = [
  {
    bg: "bg-primary",
    text: "text-primary",
    accentText: "text-quaternary",
    accentBg: "bg-quaternary",
    fg: "text-primary-foreground",
    border: "border-primary/20",
    lightBg: "bg-primary/20",
    navActive: "bg-primary text-primary-foreground shadow-sm",
    navHover: "hover:bg-primary/20 hover:text-primary focus:bg-primary/20 focus:text-primary",
    navMobileActive: "text-primary bg-primary/5 font-bold",
  },
  {
    bg: "bg-secondary",
    text: "text-secondary",
    accentText: "text-primary",
    accentBg: "bg-primary",
    fg: "text-secondary-foreground",
    border: "border-secondary/20",
    lightBg: "bg-secondary/20",
    navActive: "bg-secondary text-secondary-foreground shadow-sm",
    navHover: "hover:bg-secondary/20 hover:text-secondary focus:bg-secondary/20 focus:text-secondary",
    navMobileActive: "text-secondary bg-secondary/5 font-bold",
  },
  {
    bg: "bg-senary",
    text: "text-secondary",
    accentText: "text-secondary",
    accentBg: "bg-secondary",
    fg: "text-tertiary-foreground",
    border: "border-senary/20",
    lightBg: "bg-senary/20",
    navActive: "bg-senary text-senary-foreground shadow-sm",
    navHover: "hover:bg-senary/20 hover:text-senary focus:bg-senary/20 focus:text-senary",
    navMobileActive: "text-senary bg-senary/5 font-bold",
  },
  {
    bg: "bg-quaternary",
    text: "text-quaternary",
    accentText: "text-quinary",
    accentBg: "bg-quinary",
    fg: "text-quaternary-foreground",
    border: "border-quaternary/20",
    lightBg: "bg-quaternary/20",
    navActive: "bg-quaternary text-quaternary-foreground shadow-sm",
    navHover: "hover:bg-quaternary/20 hover:text-quaternary focus:bg-quaternary/20 focus:text-quaternary",
    navMobileActive: "text-quaternary bg-quaternary/5 font-bold",
  },
  {
    bg: "bg-quinary",
    text: "text-quinary",
    accentText: "text-quaternary",
    accentBg: "bg-quaternary",
    fg: "text-quinary-foreground",
    border: "border-quinary/20",
    lightBg: "bg-quinary/20",
    navActive: "bg-quinary text-quinary-foreground shadow-sm",
    navHover: "hover:bg-quinary/20 hover:text-quinary focus:bg-quinary/20 focus:text-quinary",
    navMobileActive: "text-quinary bg-quinary/5 font-bold",
  },
  {
    bg: "bg-senary",
    text: "text-senary",
    accentText: "text-tertiary",
    accentBg: "bg-tertiary",
    fg: "text-senary-foreground",
    border: "border-senary/20",
    lightBg: "bg-senary/20",
    navActive: "bg-senary text-senary-foreground shadow-sm",
    navHover: "hover:bg-senary/20 hover:text-senary focus:bg-senary/20 focus:text-senary",
    navMobileActive: "text-senary bg-senary/5 font-bold",
  },
];
